### ISSUE TITLE
Evaluate and potentially rework logging

### ISSUE THREAD

**Issue by theganyo** [apigee/apigee-remote-service-golib#10]
Focus on standardization and structure for supportability and automated issue detection.

**Comment by rockspore** [comment]
Just seeing this: https://github.com/apigee/apigee-remote-service-golib/blob/2d36b2586f3d6066784bad9f4b7b0524fa69e41c/analytics/fluentd_uploader.go#L94, should we add a similar debug log to the saas uploader?

**Comment by theganyo** [comment]
Yes, I think so.
