### ISSUE TITLE
Quota bucket identifiers for multiple OperationConfigs with the same apiSource

### ISSUE THREAD

**Issue by rockspore** [apigee/apigee-remote-service-golib#34]
The following API product is allowed by Apigee. Those two `operationConfigs` have the same `apiSource` for the purpose of differentiating quotas for different HTTP methods. Current implementation of the quota bucket results in same identifier for those two `operationConfigs` and therefore, when `/get`'s quota is depleted, calling `/post` will return 403 as well.
```
{
  "name": "some API product",
  ...
  "operationGroup": {
    "operationConfigs": [
      {
        "apiSource": "httpbin.default.svc.cluster.local",
        "operations": [
          {
            "resource": "/get",
            "methods": [
              "GET"
            ]
          }
        ],
        "quota": {
          "limit": "5",
          "interval": "1",
          "timeUnit": "minute"
        }
      },
      {
        "apiSource": "httpbin.default.svc.cluster.local",
        "operations": [
          {
            "resource": "/post",
            "methods": [
              "POST"
            ]
          }
        ],
        "quota": {
          "limit": "10",
          "interval": "1",
          "timeUnit": "minute"
        }
      }
    ],
    "operationConfigType": "remoteservice"
  },
  ...
}
```

**Comment by theganyo** [comment]
Hmm. This seems impossible to address without the API introducing an identifier of some kind for operationConfigs.

**Comment by rockspore** [comment]
> Hmm. This seems impossible to address without the API introducing an identifier of some kind for operationConfigs.

I agree. Yet it seems to be a totally valid use case for me.

**Comment by rockspore** [comment]
Does it make sense if we append a hash to the identifier based on the serialized struct?

**Comment by theganyo** [comment]
We could, although it would orphan the counter anytime a change was made to the operationConfig. I guess we could slightly limit the blast radius by just hashing `operations` section. What do you think, @srinandan ?

**Comment by rockspore** [comment]
And if we have `operations` sorted the hash should be consistent.

**Comment by theganyo** [comment]
Right. Sounds good. Let's do that for now at least.
