### ISSUE TITLE
address remaining reviewdog issues

### ISSUE THREAD

**Issue by theganyo** [apigee/apigee-remote-service-golib#9]
See "filtered issues". Example:

https://github.com/apigee/apigee-remote-service-golib/runs/924040521?check_suite_focus=true

**Comment by rockspore** [comment]
The analytics manager never returns an error: https://github.com/apigee/apigee-remote-service-golib/blob/51204cba3e47b31658dbc84613ecc5017fe3e025/analytics/manager.go#L190

I am thinking about changing it to return nothing but it may break the -envoy repo. Alternatively I will just mute those error checks. Which one is preferable?

**Comment by theganyo** [comment]
It looks like it would only break a test. We could do that if you'd like.

**Comment by rockspore** [comment]
> It looks like it would only break a test. We could do that if you'd like.

Done. The world is cleaner now.
