### ISSUE TITLE
jwks.AutoRefresh does not have flexibility to inject errorHandler for error logging

### ISSUE THREAD

**Issue by rockspore** [apigee/apigee-remote-service-golib#92]
Should we switch to our own backoff loop? @theganyo

**Comment by theganyo** [comment]
Yeah... it looks like the auto-refresh has no reporting at all other than calling Refresh() directly. 
https://github.com/lestrrat-go/jwx/blob/0808fe12047a86ffa7470611e32864cd9217a7fe/jwk/refresh.go#L278

It should be easy enough to just hook this into our looper, we'd just need to add the calculations for refresh time.

**Comment by rockspore** [comment]
Sounds good. So I suppose we only need a constant-interval loop to invoke `Refresh()` and the `AutoFresh` will still be doing the work behind the scene by itself.

**Comment by theganyo** [comment]
Alternatively, we could propose an error handler PR for the library.

**Comment by rockspore** [comment]
> Alternatively, we could propose an error handler PR for the library.

Yeah that sounds compelling. Maybe we should implement the temporary solution while we also propose that feature since the latter may take a while to go into a release. WDYT?

**Comment by theganyo** [comment]
True. But since we need to create a fork to do that anyway, maybe we can simply point to the go.mod to our fork in the meantime?

**Comment by rockspore** [comment]
> True. But since we need to create a fork to do that anyway, maybe we can simply point to the go.mod to our fork in the meantime?

Sounds good! Let me take a shot.
