### ISSUE TITLE
A new variant for path.Tree.Find() is needed

### ISSUE THREAD

**Issue by rockspore** [apigee/apigee-remote-service-golib#94]
Basepaths will need to be stripped from the request path. When matching for basepaths, the result should included the matched part of the actual request path for correct trimming. Otherwise, any basepath that include `*` will not be working properly.

**Comment by theganyo** [comment]
It may be easier and more useful to change the existing Find methods to return the resolved path.

**Comment by rockspore** [comment]
Sounds good. Will give a shot.
